### ISSUE TITLE
Refactor Math functions

### ISSUE THREAD

**Issue by AlBuSoft** [FartSolutions/Extended-C-Module#100]
## Description
Refactor all functions, move them from the source file to the inline file. In addition, a few more functions are to be added.

## Details
Projekt: "ecm.math"
Datei: "functions.hpp" "functions.inl"
Namespace: "ecm::math"

## Tasks
- [ ] Basic functions
  - [ ] Cbrt
  - [ ] Ceil
  - [ ] Floor
  - [ ] Exp
  - [ ] Frexp
  - [ ] Ldexp
  - [ ] Hypot
  - [ ] Fmax
  - [ ] Fmin
- [ ] Trigonometry functions
  - [ ] Cos, Acos, Cosh, Acosh
  - [ ] Sin, Asin, Sinh, Asinh
  - [ ] Tan, Atan, Tanh, Atanh
  - [ ] Log, Log2, Log10, Log1p
- [ ] Basic SIMD functions:
  - [ ] `__m128 Fma(__m128 a, __m128 b, __m128 c)`
  - [ ] `__m128 SplatX(__m128 v)`
  - [ ] `__m128 SplatY(__m128 v)`
  - [ ] `__m128 SplatZ(__m128 v)`
  - [ ] `__m128 SplatW(__m128 v)`
- [ ] Add all comments
- [ ] Implement SIMD functions for Matrix4x4 operators
