### ISSUE TITLE
Math: Lerp and Clamp functions

### ISSUE THREAD

**Issue by AlBuSoft** [FartSolutions/Extended-C-Module#87]
## Description
Lerp function for calculation of linear interpolation and a Clamp function, but not for vectors, because they don't have the needed binary operators.

## Details
Projekt: "ecm.math"
Datei: "functions.hpp" "functions.inl" "Vector2.hpp" "Vector2.inl" "Vector3.hpp" "Vector3.inl" "Vector4.hpp" "Vector4.inl"
Namespace: "ecm::math"

## Tasks
- [x] float Lerp(float a, float b, float t)
- [x] Vector2 Lerp(Vector2 a, Vector2 b, float t)
- [x] Vector3 Lerp(Vector3 a, Vector3 b, float t)
- [x] Vector4 Lerp(Vector4 a, Vector4 b, float t)
- [x] Vector2 Lerp(Vector2 a, Vector2 b, Vector2 t)
- [x] Vector3 Lerp(Vector3 a, Vector3 b, Vector3 t)
- [x] Vector4 Lerp(Vector4 a, Vector4 b, Vector4 t)
- [x] float Clamp(float a, float b, float t)
