### ISSUE TITLE
Redesign of Vector2 code

### ISSUE THREAD

**Issue by AlBuSoft** [FartSolutions/Extended-C-Module#89]
## Description
Revision of the vector2 functions for more efficiency and less susceptibility to errors.

## Details
Projekt: "ecm.math"
Datei: "vector2.hpp" "vector2.inl"
Namespace: "ecm::math"

## Tasks
- [x] Change the type name from `_Ty` to `T`
- [x] Add typedefs for the vector types.
- [x] Add more contructors:
  - [x] `vec(vec<T> const&)`
  - [x] `vec(T)`
  - [x] `vec(vec<U> const&)`
- [x] Unary arithmetic operators (all returns `vec<T>&`):
  - [x] `operator=(vec<T> const&)`
  - [x] `operator=(vec<U> const&)`
  - [x] `operator+=(U)`
  - [x] `operator+=(vec<U> const&)`
  - [x] `operator-=(U)`
  - [x] `operator-=(vec<U> const&)`
  - [x] `operator*=(U)`
  - [x] `operator*=(vec<U> const&)`
  - [x] `operator/=(U)`
  - [x] `operator/=(vec<U> const&)`
- [x] Increment and decrement operators:
  - [x] `operator++()`
  - [x] `operator--()`
  - [x] `operator++(int)`
  - [x] `operator--(int)`
- [x]  Boolean operators (analog):
  - [x] `operator==(vec<T> const&, vec<T> const&)`
  - [x] `operator!=(vec<T> const&, vec<T> const&)`
  - [x] `operator&&(vec<bool> const&, vec<bool> const&)`
  - [x] `operator||(vec<bool> const&, vec<bool> const&)`
- [x] Unary arithmetic operators (analog):
  - [x] `operator+(vec<T> const&)`
  - [x] `operator+(vec<T> const&)`
- [x] Binary operators (analog):
  - [x] `operator+(vec2<T> const&, U)`
  - [x] `operator+(vec2<T> const&, vec2<U> const&)`
  - [x] `operator-(vec2<T> const&, U)`
  - [x] `operator-(vec2<T> const&, vec2<U> const&)`
  - [x] `operator*(vec2<T> const&, U)`
  - [x] `operator*(vec2<T> const&, vec2<U> const&)`
  - [x] `operator/(vec2<T> const&, U)`
  - [x] `operator/(vec2<T> const&, vec2<U> const&)`
- [x] Add all comments
- [x] New type definitions
