### ISSUE TITLE
Math: Refactor Matrix4x4 struct

### ISSUE THREAD

**Issue by AlBuSoft** [FartSolutions/Extended-C-Module#98]
## Description
Revision of the matrix4x4 for more efficiency and less susceptibility to errors.

## Details
Projekt: "ecm.math"
Datei: "matrix4x4.hpp" "matrix4x4.inl"
Namespace: "ecm::math"

## Tasks
- [x] Add generic type `T` and rename `Matrix4x4` to `Matrix4x4_Base`
- [x] Add typedefs for the vector types
- [x] Constructors:
  - [x] `mat()`
  - [x] `mat(mat<T> m)`
  - [x] `mat(T s)`
  - [x] `mat(T x/y/z/w 1-4)`
  - [x] `mat(vec4 v 1-4)`
  - [x] `mat(X/Y/Z/W 1-4 x/y/z/w 1-4)`
  - [x] `mat(V 1-4 v 1-4)`
  - [x] `mat(mat<U> m)`
- [x] Access operators:
  - [x] `column_type& operator[](uint8 i)`
  - [x] `column_type const& operator[](uint8 i) const`
- [x] Unary arithmetic operators:
  - [x] `operator=(mat<U> const& m)`
  - [x] `operator+=(U s)`
  - [x] `operator+=(mat<U> const& m)`
  - [x] `operator-=(U s)`
  - [x] `operator-=(mat<U> const& m)`
  - [x] `operator*=(U s)`
  - [x] `operator*=(mat<U> const& m)`
  - [x] `operator/=(U s)`
  - [x] `operator/=(mat<U> const& m)`
- [x] Increment and decrement operators:
  - [x] `operator++()`
  - [x] `operator--()`
  - [x] `operator++(int)`
  - [x] `operator--(int)`
- [x] Boolean operators (analog):
  - [x] `operator==(mat<T> const& m1, mat<T> const& m2)`
  - [x] `operator!=(mat<T> const& m1, mat<T> const& m2)`
- [x] Unary operators (analog):
  - [x] `operator+(mat<T> const& m)`
  - [x] `operator-(mat<T> const& m)`
- [x] Binary operators (analog):
  - [x] `mat<T> operator+(mat<T> const& m, U scalar)`
  - [x] `mat<T> operator+(T scalar, mat<U> const& m)`
  - [x] `mat<T> operator+(mat<T> const& m1, mat<U> const& m2)`
  - [x] `mat<T> operator-(mat<T> const& m, U scalar)`
  - [x] `mat<T> operator-(T scalar, mat<U> const& m)`
  - [x] `mat<T> operator-(mat<T> const& m1, mat<U> const& m2)`
  - [x] `mat<T> operator*(mat<T> const& m, U scalar)`
  - [x] `mat<T> operator*(T scalar, mat<U> const& m)`
  - [x] `typename mat<T>::column_type operator*(mat<T> const& m, typename mat<U>::row_type const& v)`
  - [x] `typename mat<T>::row_type operator*(typename mat<T>::column_type const& v, mat<U> const& m)`
  - [x] `mat<T> operator*(mat<T> const& m1, mat<U> const& m2)`
  - [x] `mat<T> operator/(mat<T> const& m, U scalar)`
  - [x] `mat<T> operator/(T scalar, mat<U> const& m)`
  - [x] `typename mat<T>::column_type operator/(mat<T> const& m, typename mat<U>::row_type const& v)`
  - [x] `typename mat<T>::row_type operator/(typename mat<T>::column_type const& v, mat<U> const& m)`
  - [x] `mat<T> operator/(mat<T> const& m1, mat<U> const& m2)`
- [x] Add all comments
- [x] Add new type definitions (e.g. `Matrix4x4`, `Matrix4x4i`, ...)
